spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: caffeine
    

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  secret: ${RAZORPAY_SECRET}

fraud:
  url: ${FRAUD_ML_URL}

loan:
  url: ${LOAN_CHECK_URL}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

frontend:
  url: ${FRONTEND_URL}

gemini:
  key: ${GEMINI_KEY}
security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: yourbank
    access-token-minutes: 30
    refresh-token-days: 30


