spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fraud_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: subham


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cache:
    type: redis






razorpay:
  key-id: "rzp_test_RVPxvjAjcRvhXL"
  secret: "QKwbfAzto7W4s4P4nZz4UkFi"

fraud:
  url: "http://localhost:5000/predict"

loan:
  url: "http://localhost:5001/predictloan"

frontend:
  url: "http://localhost:3000/"

security:
  jwt:
    secret: "fvbkwnclslanccuruivbrwirhfvbwehibcwiuefgbwekbcakhefbwyibcsdhicdwjbw"
    issuer: "yourbank-dev"
    access-token-minutes: 60
    refresh-token-days: 30


