spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  secret: ${RAZORPAY_SECRET}

fraud:
  url: ${FRAUD_ML_URL}

loan:
  url: ${LOAN_CHECK_URL}

frontend:
  url: ${FRONTEND_URL}

gemini:
  key: ${GEMINI}

admin:
  username: ${ADMINUSER}
  password: ${ADMINPASSWORD}
security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: yourbank
    access-token-minutes: 30
    refresh-token-days: 30

logging:
  level:
    root: INFO
    org.springframework.data.redis: INFO